### ISSUE TITLE
Retrieve remote static key?

### ISSUE THREAD

**Issue by CertainLach** [jmlepisto/clatter#2]
How can I get other party static key (for authentication) while using X patterns?

This method exists in other noise protocol implementations, but I can't find it in this one.

https://docs.rs/snow/latest/snow/struct.HandshakeState.html#method.get_remote_static
https://docs.rs/noise-protocol/0.2.0/noise_protocol/struct.HandshakeState.html#method.get_rs

**Comment by jmlepisto** [comment]
Thanks for pointing this out! Clatter is definitely missing this feature.

I'm just finishing up other changes for v1.1.0 so you can expect a fix for this also in a few days :)

**Comment by CertainLach** [comment]
Remote ephemeral key would also be useful for noise pipe implementation (However, I'm not sure if it is already possible to implement noise pipe here?)

**Comment by david415** [comment]
> How can I get other party static key (for authentication) while using X patterns?
> 
> This method exists in other noise protocol implementations, but I can't find it in this one.
> 
> https://docs.rs/snow/latest/snow/struct.HandshakeState.html#method.get_remote_static https://docs.rs/noise-protocol/0.2.0/noise_protocol/struct.HandshakeState.html#method.get_rs

This feature is absolutely required for anything I would do with Noise.
Wait wait wait... actually ACTUALLY is it even possible to perform authentication without this feature!?

**Comment by CertainLach** [comment]
>  Wait wait wait... actually ACTUALLY is it even possible to perform authentication without this feature!?

You can pre-share static key and use K pattern instead of X as the form of authn

**Comment by david415** [comment]
> > Wait wait wait... actually ACTUALLY is it even possible to perform authentication without this feature!?
> 
> You can pre-share static key and use K pattern instead of X as the form of authn. Wireguard does that (Noise_IK)

Okay that makes sense. I'm very biased here because my mixnet project, Katzenpost has been using Noise XX variations for many years now.

**Comment by jmlepisto** [comment]
Sorry for the wait! I got sidetracked by Nyquist interoperability testing which proved to be unexpectedly difficult with some findings. Anyway, the changes are now in and I'm going to bake a new release very soon.
